-- Add missing Branch enum values
ALTER TYPE "Branch" ADD VALUE IF NOT EXISTS 'ERUDITION';
ALTER TYPE "Branch" ADD VALUE IF NOT EXISTS 'RHETORIC';
ALTER TYPE "Branch" ADD VALUE IF NOT EXISTS 'INTUITION';
